fix: package name on windows

diff --git a/.github/workflows/build-package-windows.yml b/.github/workflows/build-package-windows.yml
--- a/.github/workflows/build-package-windows.yml
+++ b/.github/workflows/build-package-windows.yml
@@ -41,21 +41,21 @@ jobs:
           cd build
           cpack -G NSIS64 -C ${{ matrix.build_type }}
 
-#      - name: Extract Version from Release
-#        shell: pwsh
-#        run: |
-#          cd build
-#          $exeFile = Get-ChildItem -Filter "ads-*-Windows.exe" | Select-Object -First 1
-#          if ($exeFile.Name -match "ads-([0-9]+\.[0-9]+\.[0-9]+)-Windows.exe") {
-#            echo "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-#          } else {
-#            echo "Failed to extract version"
-#            exit 1
-#          }
+      - name: Extract Version from Release
+        shell: pwsh
+        run: |
+          cd build
+          $exeFile = Get-ChildItem -Filter "ads-*-Windows.exe" | Select-Object -First 1
+          if ($exeFile.Name -match "ads-([0-9]+\.[0-9]+\.[0-9]+)-Windows.exe") {
+            echo "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+          } else {
+            echo "Failed to extract version"
+            exit 1
+          }
 
       - name: Release the Package
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: "1"
-          name: "1"
+          tag_name: "${{ env.VERSION }}"
+          name: "${{ env.VERSION }}"
           files: build/ads-*-${{ matrix.build_type }}.exe
