fix: default package name

diff --git a/.github/workflows/build-package-linux.yml b/.github/workflows/build-package-linux.yml
--- a/.github/workflows/build-package-linux.yml
+++ b/.github/workflows/build-package-linux.yml
@@ -32,21 +32,21 @@ jobs:
           cd build
           cpack -G DEB
 
-      - name: Extract Version and Set Tag Name
-        run: |
-          cd build
-          debFile=$(ls ads_*.deb | head -n 1)
-          if [[ "$debFile" =~ ads_([0-9]+\.[0-9]+\.[0-9]+)_.*.deb ]]; then
-            VERSION=${BASH_REMATCH[1]}
-            echo "VERSION=$VERSION" >> $GITHUB_ENV
-          else
-            echo "Failed to extract version"
-            exit 1
-          fi
+#      - name: Extract Version and Set Tag Name
+#        run: |
+#          cd build
+#          debFile=$(ls ads_*.deb | head -n 1)
+#          if [[ "$debFile" =~ ads_([0-9]+\.[0-9]+\.[0-9]+)_.*.deb ]]; then
+#            VERSION=${BASH_REMATCH[1]}
+#            echo "VERSION=$VERSION" >> $GITHUB_ENV
+#          else
+#            echo "Failed to extract version"
+#            exit 1
+#          fi
 
       - name: Release the Package
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: "${{ env.VERSION }}"
-          name: "${{ env.VERSION }}"
+          tag_name: "1"
+          name: "1"
           files: build/*.deb
