fix: Prevent build overwriting

diff --git a/.github/workflows/build-package-windows.yml b/.github/workflows/build-package-windows.yml
--- a/.github/workflows/build-package-windows.yml
+++ b/.github/workflows/build-package-windows.yml
@@ -41,41 +41,41 @@ jobs:
           cmake --build . --config ${{ matrix.build_type }}
 
 
-      - name: Package ADS with CPack and Rename Installer
-        shell: pwsh
-        run: |
-          cd build_twincat
-          cpack -G NSIS64 -C ${{ matrix.build_type }}
-
-          # 确保 cpack 生成了文件
-          $installer = Get-ChildItem -Filter "*.exe" | Select-Object -First 1
-          if ($installer -eq $null) { 
-            echo "Error: No installer found!" 
-            exit 1 
-          }
-
-          # 获取原始名字并添加后缀
-          $originalName = $installer.Name
-          $suffix = "${{ matrix.build_type }}".ToLower()
-          $newName = "$originalName-$suffix.exe"
-          Rename-Item -Path $installer.FullName -NewName $newName
-          cd ..
-
-          cd build_no_twincat
-          cpack -G NSIS64 -C ${{ matrix.build_type }}
-
-          # 确保 cpack 生成了文件
-          $installer = Get-ChildItem -Filter "*.exe" | Select-Object -First 1
-          if ($installer -eq $null) { 
-            echo "Error: No installer found!" 
-            exit 1 
-          }
-
-          # 获取原始名字并添加后缀
-          $originalName = $installer.Name
-          $newName = "$originalName-$suffix.exe"
-          Rename-Item -Path $installer.FullName -NewName $newName
-          cd ..
+#      - name: Package ADS with CPack and Rename Installer
+#        shell: pwsh
+#        run: |
+#          cd build_twincat
+#          cpack -G NSIS64 -C ${{ matrix.build_type }}
+#
+#          # 确保 cpack 生成了文件
+#          $installer = Get-ChildItem -Filter "*.exe" | Select-Object -First 1
+#          if ($installer -eq $null) {
+#            echo "Error: No installer found!"
+#            exit 1
+#          }
+#
+#          # 获取原始名字并添加后缀
+#          $originalName = $installer.Name
+#          $suffix = "${{ matrix.build_type }}".ToLower()
+#          $newName = "$originalName-$suffix.exe"
+#          Rename-Item -Path $installer.FullName -NewName $newName
+#          cd ..
+#
+#          cd build_no_twincat
+#          cpack -G NSIS64 -C ${{ matrix.build_type }}
+#
+#          # 确保 cpack 生成了文件
+#          $installer = Get-ChildItem -Filter "*.exe" | Select-Object -First 1
+#          if ($installer -eq $null) {
+#            echo "Error: No installer found!"
+#            exit 1
+#          }
+#
+#          # 获取原始名字并添加后缀
+#          $originalName = $installer.Name
+#          $newName = "$originalName-$suffix.exe"
+#          Rename-Item -Path $installer.FullName -NewName $newName
+#          cd ..
 
 
 
