fix: still use pwsh

diff --git a/.github/workflows/build-package-windows.yml b/.github/workflows/build-package-windows.yml
--- a/.github/workflows/build-package-windows.yml
+++ b/.github/workflows/build-package-windows.yml
@@ -21,10 +21,10 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Configure and Build ADS
-        shell: cmd
+        shell: pwsh
         run: |
-          set TwinCAT_ROOT=C:\TwinCAT
-          echo TwinCAT_ROOT is set to %TwinCAT_ROOT%
+          $env:TwinCAT_ROOT="C:\TwinCAT"
+          echo "TwinCAT_ROOT is set to $env:TwinCAT_ROOT"
           
           mkdir build
           cd build
@@ -34,48 +34,30 @@ jobs:
 
 
       - name: Extract Version from Release
-        shell: cmd
+        shell: pwsh
         run: |
-          @echo off
-          setlocal EnableDelayedExpansion
           cd build
-          for /f "delims=" %%i in ('dir /b /o:-n ads-*.exe') do (
-            set "exeFile=%%i"
-            goto found
-          )
-          :found
-          if defined exeFile (
-            rem 去掉前缀 "ads-" 和后缀 ".exe" 提取版本号
-            set "version=!exeFile:ads-=!"
-            set "version=!version:.exe=!"
-            echo VERSION=!version!>> %GITHUB_ENV%
-          ) else (
-            echo Failed to extract version
-            exit /b 1
-          )
-    
+          $exeFile = Get-ChildItem -Filter "ads-*.exe" | Sort-Object Name -Descending | Select-Object -First 1
+          if ($exeFile.Name -match "ads-([\d\.]+)") {
+            echo "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+          } else {
+            echo "Failed to extract version"
+            exit 1
+          }
 
       - name: Rename Executables add build_type
-        shell: cmd
+        shell: pwsh
         run: |
-          @echo off
-          setlocal EnableDelayedExpansion
           cd build
-          for /f "delims=" %%i in ('dir /b /o:-n ads-*.exe') do (
-            set "exeFile=%%i"
-            goto found
-          )
-          :found
-          if defined exeFile (
-            rem 将 .exe 替换为 -<build_type>.exe
-            set "newName=!exeFile:.exe=-${{ matrix.build_type }}.exe!"
-            ren "!exeFile!" "!newName!"
-            echo Renamed !exeFile! to !newName!
-          ) else (
-            echo No executable found!
-            exit /b 1
-          )
-
+          $exeFile = Get-ChildItem -Filter "ads-*.exe" | Sort-Object Name -Descending | Select-Object -First 1
+          if ($exeFile) {
+            $newName = $exeFile.Name -replace "(?<=ads-[\d\w\.-]+)(\.exe)$", "-${{ matrix.build_type }}.exe"
+            Rename-Item -Path $exeFile.FullName -NewName $newName
+            echo "Renamed $($exeFile.Name) to $newName"
+          } else {
+            echo "No executable found!"
+            exit 1
+          }
 
       - name: Release the Package
         uses: softprops/action-gh-release@v2
